# bootc-image-builder configuration file
# This file configures user creation and SSH key setup for the bootable image

[[customizations.user]]
name = "${BOOTC_ADMIN_USERNAME}"
description = "Administrator user"
password = "${BOOTC_ADMIN_PASSWORD}"
key = "${BOOTC_SSH_PUBLIC_KEY}"
groups = ["wheel"]
