name: Build bootc Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: localhost/fedora-bootc:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y podman qemu-utils

      - name: Build container image
        run: |
          podman build -t ${{ env.IMAGE_NAME }} container/

      - name: Verify container image
        run: |
          podman images | grep fedora-bootc

      - name: Install bootc-image-builder
        run: |
          podman pull quay.io/centos-bootc/bootc-image-builder:latest

      - name: Create output directory
        run: mkdir -p output

      - name: Build bootc disk image
        run: |
          sudo podman run --rm --privileged \
            --security-opt label=type:unconfined_t \
            -v $(pwd)/output:/output:Z \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type qcow2 \
            --output /output \
            ${{ env.IMAGE_NAME }}

      - name: List and verify output files
        run: |
          echo "Output directory contents:"
          ls -la output/
          echo "Checking for qcow2 files:"
          find output/ -name "*.qcow2" -exec ls -lh {} \;

      - name: Upload disk image artifact
        uses: actions/upload-artifact@v4
        with:
          name: fedora-bootc-image-${{ github.run_number }}
          path: output/*.qcow2
          retention-days: 3
          if-no-files-found: error

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ github.run_number }}
          path: |
            output/*.log
            output/*.txt
          retention-days: 3
