name: Build bootc Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}/fedora-bootc

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y podman

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        run: |
          podman build -t ${{ env.IMAGE_NAME }}:latest container/

      - name: Push container image to registry
        run: |
          podman push ${{ env.IMAGE_NAME }}:latest

      - name: Install bootc-image-builder
        run: |
          sudo podman pull quay.io/centos-bootc/bootc-image-builder:latest

      - name: Pull container image for bootc-image-builder
        run: |
          sudo podman pull ${{ env.IMAGE_NAME }}:latest

      - name: Create output directory
        run: mkdir -p output

      - name: Build bootc disk image
        run: |
          sudo podman run --rm --privileged \
            --security-opt label=type:unconfined_t \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            -v $(pwd)/output:/output:Z \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type qcow2 \
            --output /output \
            ${{ env.IMAGE_NAME }}:latest

      - name: List and verify output files
        run: |
          echo "Output directory contents:"
          ls -la output/
          echo "Checking for qcow2 files:"
          find output/ -name "*.qcow2" -exec ls -lh {} \;

      - name: Upload disk image artifact
        uses: actions/upload-artifact@v4
        with:
          name: fedora-bootc-image-${{ github.run_number }}
          path: output/*.qcow2
          retention-days: 3
          if-no-files-found: error

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ github.run_number }}
          path: |
            output/*.log
            output/*.txt
          retention-days: 3
